packages:
  - packages/*

catalog:
  '@inquirer/select': ^5.1.2
  bumpp: ^11.0.1
  cac: ^7.0.0
  changelogen: ^0.6.2
  consola: ^3.4.2
  defu: ^6.1.4
  esconf: ~1.0.0
  ofetch: ^1.5.1
  picospinner: ^3.0.0
  semver: ^7.7.4
  tinyexec: ^1.0.4
  tinyglobby: ^0.2.15

catalogs:
  dev:
    '@types/node': ^25.5.0
    '@types/semver': ^7.7.1
    '@vill-v/tsconfig': ^1.0.1
    oxfmt: ^0.41.0
    oxlint: ^1.56.0
    publint: ^0.3.18
    taze: ^19.10.0
    tsdown: ^0.21.4
    turbo: ^2.8.17
    typescript: ^5.9.3
    unplugin-unused: ^0.5.7
    vitest: ^4.1.0

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
