//! Cargo.toml 插件矩阵（ADR-0003）：toml_edit 保格式更新 `[package].version`，
//! workspace 继承探测，按 crate name 定向同步 `Cargo.lock` 的 `[[package]]` 条目。

use std::fs;
use std::path::Path;

use bumpp_core::plugins::{dispatch_file as update_file, FilesError as UpdateError, UpdateOutcome};
use tempfile::TempDir;

const CURRENT: &str = "1.0.0";
const NEW: &str = "2.0.0";

fn bump(dir: &TempDir) -> Result<UpdateOutcome, UpdateError> {
  update_file(
    Path::new("Cargo.toml"),
    &dir.path().join("Cargo.toml"),
    CURRENT,
    NEW,
  )
}

fn read(dir: &TempDir, name: &str) -> String {
  fs::read_to_string(dir.path().join(name)).unwrap()
}

fn write(dir: &TempDir, name: &str, content: &str) {
  fs::write(dir.path().join(name), content).unwrap();
}

/// 标准 Cargo.lock 骨架（version = 4 元数据行不得被触碰）
fn lock(entries: &str) -> String {
  format!(
    "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{entries}"
  )
}

#[test]
fn literal_version_updated_preserving_format_and_comments() {
  let dir = TempDir::new().unwrap();
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"demo\"\nversion = \"1.0.0\" # 行内注释保留\nedition = \"2021\"\n\n[dependencies]\nserde = \"1.0.0\"\n",
  );
  write(
    &dir,
    "Cargo.lock",
    &lock(
      "[[package]]\nname = \"demo\"\nversion = \"1.0.0\"\ndependencies = [\n \"serde\",\n]\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"aaaa\"\n",
    ),
  );
  let outcome = bump(&dir).unwrap();
  assert_eq!(
    outcome,
    UpdateOutcome::UpdatedWith(vec![dir.path().join("Cargo.lock")])
  );
  // 仅 version 值被替换：键序、空行、行内注释、依赖表全部保留
  assert_eq!(
    read(&dir, "Cargo.toml"),
    "[package]\nname = \"demo\"\nversion = \"2.0.0\" # 行内注释保留\nedition = \"2021\"\n\n[dependencies]\nserde = \"1.0.0\"\n"
  );
  // lock 仅 demo 条目被定向更新；serde 条目（version 恰好同为 1.0.0）不动
  assert_eq!(
    read(&dir, "Cargo.lock"),
    lock(
      "[[package]]\nname = \"demo\"\nversion = \"2.0.0\"\ndependencies = [\n \"serde\",\n]\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"aaaa\"\n"
    )
  );
}

#[test]
fn unrelated_tables_versions_are_never_rewritten() {
  let dir = TempDir::new().unwrap();
  // [dependencies] / [dev-dependencies] 中存在与 current 同值的版本字段——专门断言不被改写
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n\n[dependencies]\npinned = \"1.0.0\"\n\n[dev-dependencies]\nalso-pinned = \"1.0.0\"\n",
  );
  write(
    &dir,
    "Cargo.lock",
    &lock("[[package]]\nname = \"demo\"\nversion = \"1.0.0\"\n"),
  );
  let outcome = bump(&dir).unwrap();
  assert!(matches!(outcome, UpdateOutcome::UpdatedWith(_)));
  let updated = read(&dir, "Cargo.toml");
  assert!(updated.contains("[package]\nname = \"demo\"\nversion = \"2.0.0\""));
  assert!(updated.contains("pinned = \"1.0.0\""), "依赖表版本不得改写");
  assert!(
    updated.contains("also-pinned = \"1.0.0\""),
    "dev 依赖表版本不得改写"
  );
}

#[test]
fn already_new_version_is_skipped_untouched() {
  let dir = TempDir::new().unwrap();
  let original = "[package]\nname = \"demo\"\nversion = \"2.0.0\"\n";
  write(&dir, "Cargo.toml", original);
  let outcome = bump(&dir).unwrap();
  assert_eq!(outcome, UpdateOutcome::Skipped);
  assert_eq!(read(&dir, "Cargo.toml"), original, "已是最新不应重写文件");
}

#[test]
fn missing_version_is_skipped() {
  let dir = TempDir::new().unwrap();
  let original = "[package]\nname = \"demo\"\nedition = \"2021\"\n";
  write(&dir, "Cargo.toml", original);
  let outcome = bump(&dir).unwrap();
  assert_eq!(outcome, UpdateOutcome::Skipped);
  assert_eq!(read(&dir, "Cargo.toml"), original);
}

#[test]
fn workspace_inherited_member_is_skipped_untouched() {
  let dir = TempDir::new().unwrap();
  // 成员继承根版本：强写字面量会破坏继承，按 ADR-0003 跳过（根清单作为显式文件项自行处理）
  let original = "[package]\nname = \"demo\"\nversion.workspace = true\n";
  write(&dir, "Cargo.toml", original);
  let outcome = bump(&dir).unwrap();
  assert_eq!(outcome, UpdateOutcome::Skipped);
  assert_eq!(read(&dir, "Cargo.toml"), original);
}

#[test]
fn root_package_inheriting_own_workspace_section_updates_workspace_version() {
  let dir = TempDir::new().unwrap();
  // 根 package 以 version.workspace = true 继承本文件 [workspace.package]：
  // 更新 [workspace.package].version，[package] 不强写字面量
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"root-pkg\"\nversion.workspace = true\n\n[workspace]\nmembers = [\".\"]\n\n[workspace.package]\nversion = \"1.0.0\"\nedition = \"2021\"\n",
  );
  write(
    &dir,
    "Cargo.lock",
    &lock("[[package]]\nname = \"root-pkg\"\nversion = \"1.0.0\"\n"),
  );
  let outcome = bump(&dir).unwrap();
  assert!(matches!(outcome, UpdateOutcome::UpdatedWith(_)));
  let updated = read(&dir, "Cargo.toml");
  assert!(
    updated.contains("version.workspace = true"),
    "继承形态不得被字面量覆盖"
  );
  assert!(updated.contains("[workspace.package]\nversion = \"2.0.0\""));
  assert!(updated.contains("[workspace]\nmembers = [\".\"]"));
}

#[test]
fn virtual_workspace_root_updates_and_sweeps_member_lock_entries() {
  let dir = TempDir::new().unwrap();
  write(
    &dir,
    "Cargo.toml",
    "[workspace]\nmembers = [\"crates/a\", \"crates/b\"]\n\n[workspace.package]\nversion = \"1.0.0\"\n",
  );
  write(
    &dir,
    "Cargo.lock",
    &lock(
      "[[package]]\nname = \"member-a\"\nversion = \"1.0.0\"\n\n[[package]]\nname = \"member-b\"\nversion = \"1.0.0\"\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"bbbb\"\n\n[[package]]\nname = \"odd-member\"\nversion = \"0.3.0\"\n",
    ),
  );
  let outcome = bump(&dir).unwrap();
  assert_eq!(
    outcome,
    UpdateOutcome::UpdatedWith(vec![dir.path().join("Cargo.lock")])
  );
  assert_eq!(
    read(&dir, "Cargo.toml"),
    "[workspace]\nmembers = [\"crates/a\", \"crates/b\"]\n\n[workspace.package]\nversion = \"2.0.0\"\n"
  );
  // 无 source 且 version == current 的成员条目被更新；registry 依赖与版本不符的成员不动
  assert_eq!(
    read(&dir, "Cargo.lock"),
    lock(
      "[[package]]\nname = \"member-a\"\nversion = \"2.0.0\"\n\n[[package]]\nname = \"member-b\"\nversion = \"2.0.0\"\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"bbbb\"\n\n[[package]]\nname = \"odd-member\"\nversion = \"0.3.0\"\n"
    )
  );
}

#[test]
fn lock_entry_missing_is_an_error_and_manifest_stays_untouched() {
  let dir = TempDir::new().unwrap();
  let original = "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n";
  write(&dir, "Cargo.toml", original);
  write(
    &dir,
    "Cargo.lock",
    &lock("[[package]]\nname = \"someone-else\"\nversion = \"1.0.0\"\n"),
  );
  let err = bump(&dir).unwrap_err();
  let message = err.to_string();
  assert!(
    message.contains("\"demo\""),
    "错误应点名缺失的 crate，实际：{message}"
  );
  assert_eq!(
    read(&dir, "Cargo.toml"),
    original,
    "lock 同步失败时清单不得先行改写（失败即报错）"
  );
}

#[test]
fn lock_version_drift_is_an_error() {
  let dir = TempDir::new().unwrap();
  let original = "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n";
  write(&dir, "Cargo.toml", original);
  // 条目存在但版本已漂移（≠ current）：同样是同步失败
  write(
    &dir,
    "Cargo.lock",
    &lock("[[package]]\nname = \"demo\"\nversion = \"0.9.0\"\n"),
  );
  let err = bump(&dir).unwrap_err();
  assert!(err.to_string().contains("\"demo\""));
  assert_eq!(read(&dir, "Cargo.toml"), original);
}

#[test]
fn missing_lock_file_updates_manifest_only() {
  let dir = TempDir::new().unwrap();
  // 无 Cargo.lock 可同步（库 crate 常见，不视为漂移）：仅更新清单
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n",
  );
  let outcome = bump(&dir).unwrap();
  assert_eq!(outcome, UpdateOutcome::Updated);
  assert_eq!(
    read(&dir, "Cargo.toml"),
    "[package]\nname = \"demo\"\nversion = \"2.0.0\"\n"
  );
}

#[test]
fn lock_is_discovered_by_walking_up_ancestors() {
  let dir = TempDir::new().unwrap();
  fs::create_dir_all(dir.path().join("crates/demo")).unwrap();
  fs::write(
    dir.path().join("crates/demo/Cargo.toml"),
    "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n",
  )
  .unwrap();
  write(
    &dir,
    "Cargo.lock",
    &lock("[[package]]\nname = \"demo\"\nversion = \"1.0.0\"\n"),
  );
  let outcome = update_file(
    Path::new("crates/demo/Cargo.toml"),
    &dir.path().join("crates/demo/Cargo.toml"),
    CURRENT,
    NEW,
  )
  .unwrap();
  // workspace 成员的 lock 位于仓库根：向上发现
  assert_eq!(
    outcome,
    UpdateOutcome::UpdatedWith(vec![dir.path().join("Cargo.lock")])
  );
  assert_eq!(
    read(&dir, "Cargo.lock"),
    lock("[[package]]\nname = \"demo\"\nversion = \"2.0.0\"\n")
  );
}

#[test]
fn invalid_toml_is_an_error_and_file_stays_untouched() {
  let dir = TempDir::new().unwrap();
  // 显式列入发版清单的文件不可解析 = 漂移风险：立即报错（ADR-0003 失败即报错，
  // 与 JsManifest 通道的上游容错 parity 是有意的不对称）
  let original = "{ not toml";
  write(&dir, "Cargo.toml", original);
  let err = bump(&dir).unwrap_err();
  assert!(
    err.to_string().starts_with("解析 Cargo.toml 失败："),
    "错误应点名相对路径，实际：{}",
    err
  );
  assert_eq!(read(&dir, "Cargo.toml"), original);
}

#[test]
fn unparseable_lock_is_an_error() {
  let dir = TempDir::new().unwrap();
  let original = "[package]\nname = \"demo\"\nversion = \"1.0.0\"\n";
  write(&dir, "Cargo.toml", original);
  write(&dir, "Cargo.lock", "{ not toml");
  let err = bump(&dir).unwrap_err();
  assert!(err.to_string().contains("Cargo.lock"));
  assert_eq!(read(&dir, "Cargo.toml"), original);
}

// ---- read_version（ADR-0009：版本解析生态化，经链分发公开面） ----

use bumpp_core::plugins::dispatch_read_version;

fn read_version_of(dir: &TempDir) -> Option<String> {
  dispatch_read_version(
    Path::new("Cargo.toml"),
    &dir.path().join("Cargo.toml"),
  )
}

#[test]
fn read_version_extracts_package_version_literal() {
  let dir = TempDir::new().unwrap();
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"demo\"\nversion = \"1.2.3\"\n",
  );
  assert_eq!(read_version_of(&dir), Some("1.2.3".into()));
}

#[test]
fn read_version_falls_back_to_workspace_package_literal() {
  let dir = TempDir::new().unwrap();
  // 虚拟 workspace 根：仅 [workspace.package].version 字面量
  write(
    &dir,
    "Cargo.toml",
    "[workspace]\nmembers = []\n\n[workspace.package]\nversion = \"7.8.9\"\n",
  );
  assert_eq!(read_version_of(&dir), Some("7.8.9".into()));
}

#[test]
fn read_version_none_for_workspace_inherited_member() {
  let dir = TempDir::new().unwrap();
  // version.workspace = true 继承形态：本文件无版本字面量
  write(
    &dir,
    "Cargo.toml",
    "[package]\nname = \"demo\"\nversion.workspace = true\n",
  );
  assert_eq!(read_version_of(&dir), None);
}

#[test]
fn read_version_none_for_broken_or_missing_manifest() {
  let dir = TempDir::new().unwrap();
  write(&dir, "Cargo.toml", "{ not toml");
  assert_eq!(read_version_of(&dir), None);
  let empty = TempDir::new().unwrap();
  assert_eq!(read_version_of(&empty), None);
}
